"""rename department

Revision ID: 5a68c36a3ff9
Revises: 69f4a3efe583
Create Date: 2024-05-28 19:03:57.478580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a68c36a3ff9'
down_revision = '69f4a3efe583'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
